apiVersion: v1
kind: Namespace
metadata:
  name: pepr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-object-storage-operator
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-object-storage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-object-storage-operator
subjects:
  - kind: ServiceAccount
    name: pepr-object-storage-operator
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-object-storage-operator
  namespace: pepr-system
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-object-storage-operator-api-token
  namespace: pepr-system
type: Opaque
data:
  value: >-
    YzBiZjVkODY5MDU0OWI2NmY4ZGI2ZDMyYjVlOGYwNzljMzAwYzBiZWVmZjY2MTk2MTM3YzUwZGQxYzQ4NWI4Mg==
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-object-storage-operator-tls
  namespace: pepr-system
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdGpDQ0FaNmdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEkwTURFeU5qRTNNalV3DQpORm9YRFRJMU1ERXlOakUzTWpVd05Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQU9CbDN3MGFuZEltRCtUdTh5S0w2Ry9RckNYMmplWVNxUlNjSm4xQ2Y0dTY2U2NsaUU2dHd6ZlpwdWl3DQpFUERKRkdhQ3BGSktzMFhBWk1CeDVDTmMvclFOSnVEeXdTRGltWVY3SE90T3RJRGZoYWxrNzZKOWV3d1h5WVp1DQpublZhdFNnbDJmcVVSSmNsdmlhN1poKzlKdDJTRDJMeFVETzB5NDdFQmwyUU93UWY4N1M4Q1VQVkNmc25MU0hRDQpKc3E2aURHWWdXTElGbi9PYS8yemtJMVRReFRvL0hYS25FVUhocFQ5bUhXNGw1UWVBQUtUMzNRSFhzWG1RUHJTDQpEZHlWdXVzOW5oaFN6S255Ym5QUno4djYrL1hLcUpQVER6dXVaajVuK0RXZXNGajNHU01wNUZBU0RPbzJpTkMrDQpIWUI5Q0JuWDJ0L3Z1Sy9wU0YvUTRaS2JsdnNDQXdFQUFhTTdNRGt3TndZRFZSMFJCREF3TG9Jc2NHVndjaTF2DQpZbXBsWTNRdGMzUnZjbUZuWlMxdmNHVnlZWFJ2Y2k1d1pYQnlMWE41YzNSbGJTNXpkbU13RFFZSktvWklodmNODQpBUUVMQlFBRGdnRUJBRHVLRWtaaTdHaGRkS2J1anJGWDk3c2NCYWNjaUVub1phOTh2R2NKTGEwNHRTY3lKcVg2DQpRNTRGUldYWmlmYjhvdE9uQ1ZIalVlbkFENXcxMXMyQnYweWFjMEtCNTJ3Z1dhUG45TEQwc3FodlFFWkxSVFRVDQpNSjBSaU5hVUtWYnJMdnh5cWNQZkdUa2JVMmFSSkRyNkljMFJWS0RKM1pOd0JIb0dSMnF2SXBQMWd5MzB2dkZFDQpYd0NUbXcwRWMvLzZUWjBQY0VLNFRkQlEvMlRZZm55dEd2OFQ1OHh3NUY5NkNDSEQzOTNFQkVod3hicXliVXRmDQpVMGNXdFJJZGd0SU0rOTM2Y1ZBdWltWXlHczFXdUpMYndDTkNLbkJjN0dWZ05YZllLR204S3dIVnZKVUFJWWlhDQo3WUorNDdkQ01GSTRmaGhRdThGYTJvNVlNZHJ6VHFZZTJWZz0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQTRHWGZEUnFkMGlZUDVPN3pJb3ZvYjlDc0pmYU41aEtwRkp3bWZVSi9pN3JwSnlXSQ0KVHEzRE45bW02TEFROE1rVVpvS2tVa3F6UmNCa3dISGtJMXordEEwbTRQTEJJT0taaFhzYzYwNjBnTitGcVdUdg0Kb24xN0RCZkpobTZlZFZxMUtDWForcFJFbHlXK0pydG1INzBtM1pJUFl2RlFNN1RManNRR1haQTdCQi96dEx3Sg0KUTlVSit5Y3RJZEFteXJxSU1aaUJZc2dXZjg1ci9iT1FqVk5ERk9qOGRjcWNSUWVHbFAyWWRiaVhsQjRBQXBQZg0KZEFkZXhlWkErdElOM0pXNjZ6MmVHRkxNcWZKdWM5SFB5L3I3OWNxb2s5TVBPNjVtUG1mNE5aNndXUGNaSXluaw0KVUJJTTZqYUkwTDRkZ0gwSUdkZmEzKys0citsSVg5RGhrcHVXK3dJREFRQUJBb0lCQUJCR014d1BMeHo3bDdHQg0KeHU1ZGVUa0t5RUZrbFR2M1pIM1RLVk55VEMvRkdYMjJVaUZxcHJyWk5TcXhBam1FUzg5M2NCVnJ4MzZxaW1RTw0Kbm40V0UzN1phVlZ0SmFhTjZKWnVyRlZBZXdUUnNTN3MzQmhMdzIzSUY5eUJEMHJ4aml2Z091UGFkdk1EVUx3Yw0KWVRheUVDeUhtRWdUdWo1VndXR1VRK1hyUE94NmhmempCZnFEc1I0cXpLY2JZWlBycTBrclJDelljTk84OUJOZQ0Kd3BHTGhQVE9vNFdnbmd5NTZrTjdCOFFRWEJHbmplZ0ZwNFlZV0lITWp0T2o0MCsrMVZYbWhTYXBMVFZOL2JJdQ0KMVBTbElpUGpvdG8wSjJTRG1icXV2Zk1QdXdpbHp3WTNBZEMwUHRGN2Y5bnN5M2VQMnpzRmNsRjRXSi9HaE9oMw0KWkVLd2dBa0NnWUVBOGU5YkhHQy9IN0lTVElVbFczTWdidnhFV1FsZmozVkdMdTFDcWtIMW1XMVcwOHYzVUZ4TA0KbnQycld0Uzl0cjhKM3k4WGVGS2cwVXdMZ3hZQWRLRmJVVlNRc2pmNFhvNG5EdllWRlBQS3g4czZoSmtJc2JSLw0KaW1pZC9GOU9BNHo2cXB6eXpEczBXMWttSnF2enMrQ1QybFdseXJVa2tPMjJEZWVYcnMraTBvY0NnWUVBN1hHRQ0KVWE5emIrdm9Mc1RZYm1xTU1QZzRqL2lrSzBDNlZzck8xZ01VZml2ZjZuNW4rRERveFl3T0pjTnhzQlp1bFlMaA0KVHZYalhvNDExeVRTRmY0V3BRTGpzZW1aZ2hDaWNGY1hOVm9ZZG5lMElpZ3gyb0M0V2grTmhKbWhuMTE0Nitrbg0KMlpDVXJ5aFhkaWd6OVYrK3pUTmhxR0hOcm9MMXZJdEdJN3JuME8wQ2dZQnBHMHZCOEdZWUp3eThJYnd4RnJzbw0KZklCVkRqVnQ1YzB2NWZQb2MrOTNVSUZBVW9TSGJSR05XMUJ1amE0K0RwRURYVG9kRkFpNTVRZTdVM3V2TDhxMA0KY3NES0xIYkMzWThxZU01LzQ4cGRNbldoMWJwcE9ibVBNQlF5NkZURVJpTkFyQjd2aTJrYnBvZGtsWit5cmdhTg0KL0ZlaTBUK3BseHhZdmh5djNaVW5VUUtCZ1FEWWdKSkRIVFNuejdYMHR4NFZoK2R1VzFiUHg4cUJlZEt1Z3R3WA0KL2RUNHVxN0FGU1JlQk5LcUZldHNlWW8zSWkwUS9MYk9GWnlOUWlSTG1OSktwVlVtZnJ6NUkyUUtXWHFUN29WRg0KNjNHMHk2OGZHZ0ZqRjgyQXQ1YUZXc1FwR01UQ2J1VWNGeDNMbklBclI3c2d1SDIwZzI0L1ozWnc4ZzU1TFpEMQ0KMFYzQWZRS0JnSFQ1ZHV1dXJJSHNJelVMa2E0ZzdHdXpCbi9LK29OQUdCL3FxMkI3M0VIZGtLNWhyc1BqamxoOA0KMHdnTjNEZkh6QUdNVEFHYW14dmFlSGNIRTBHN1lWZTQyVW5ZY29SMFRsSEQ2RVc3djRWa1RTSXBBbTR0dlZBcw0KS0Q5bEsxclZxL082cTVoUXFiSE1KbUREaVJTQUpJYVhEUW9VT3BKVy9XTTZyaHdNTUZCZA0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-object-storage-operator
  namespace: pepr-system
  labels:
    app: pepr-object-storage-operator
    pepr.dev/controller: admission
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-object-storage-operator
      pepr.dev/controller: admission
  template:
    metadata:
      annotations:
        buildTimestamp: '1706289904596'
      labels:
        app: pepr-object-storage-operator
        pepr.dev/controller: admission
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: pepr-object-storage-operator
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroup: 65532
      containers:
        - name: server
          image: ghcr.io/defenseunicorns/pepr/controller:v0.23.1
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - f05ed85b85867f21496a7a3cf24949ff6d1f76dc16c8bcbd90986875e397ba34
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          env:
            - name: PEPR_WATCH_MODE
              value: 'false'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: debug
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: api-token
              mountPath: /app/api-token
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-object-storage-operator-tls
        - name: api-token
          secret:
            secretName: pepr-object-storage-operator-api-token
        - name: module
          secret:
            secretName: pepr-object-storage-operator-module
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-object-storage-operator
  namespace: pepr-system
  labels:
    pepr.dev/controller: admission
spec:
  selector:
    app: pepr-object-storage-operator
    pepr.dev/controller: admission
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-object-storage-operator-watcher
  namespace: pepr-system
  labels:
    pepr.dev/controller: watcher
spec:
  selector:
    app: pepr-object-storage-operator-watcher
    pepr.dev/controller: watcher
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-object-storage-operator-module
  namespace: pepr-system
type: Opaque
data:
  module-f05ed85b85867f21496a7a3cf24949ff6d1f76dc16c8bcbd90986875e397ba34.js.gz: >-
    H4sIAAAAAAAAE61U34/UNhB+569w3YpLJMe71xUS8iqntvSHThQOUSEeTifhteeyZh3bHTtZoij/e+Vkjy4CykvfPPPNjD/PzOdeImnqm917UIlruDcOXqEPgGnY9hKJrwtgWNZXTQGMOtkCZWMvbQcCmfLu3jQdyp0F8d16KucUUyP83RmEggYISBdvqMecLaif76pi8igbqPJdMnmkrAeMxjtB13zNLynTEBWakGbfz+R5twN0kCCSm1MOufdIWulkY1xDlsLkVJjsOnWAFDllBxiOHnUUtwshRg9PI2U0eGvUUIFrjINsQ8Cq9bqz2YqgOjRpoHdsiYhidF6DoFf15VO+5ms6sZwivvWwrjP6P2DvfkP0KChCjqBM2qMc4nXjPMJSPAapIIrbO2blDmw+Tcw4ZTsN+ndjFwxcL8ZpYkvbohh3nbFaUBc+kEyUzDZ5/JioQLSJaXX24uor/PggW5ubbO4hpriijBrZigipC1RQvtpLdVgZ2fK4J4t3iUggUfuj+yzoI8DoYaOrh0qHjSbKdjEBEg0WEsykKw19pnwOKwR5DlfVYRMriQ25qCoNu675KQL2gGJ9QarqKE2aS3Q7UMkS9Nb6Lm+KTF0kGoL1QwsukcrNQVUcYoKWTkxDAKfBKZPHP0+brvmPG345g/2vn+BpCKedFfQJ3/ANnaZ5+eUXJaG+6E21sjJGAh8SOB2J4pL/AQ7QqOfG6TGzNmr0RdqbyOhfm1/mRaflFAOo5b641Pg8lpaTjINTpxYuqQWWo4VE2hp5rsHzyjH9YCE0xrut8i56C9z6pnj3LKdn0S0qIxc/jO10QYwjS3R26OniXXlqgKsdHInkz2SQO2NNGopvqeZ/k/+5gOgJpndTyca3e3DCTrXbFmsm+WtoTN6v3OaySGxs0HdBUC3jXsshcg392TfVX1J2ME6Lf2cwlVtbpJJfx7lBoG/wTdD5UJT82r18YFJ85FHytzKpfbFMBeqrUc7rmtsVi5J/Micop3KbEcNfQcAXs3CLwG7dXbl9tFp9T6LvUMELGYJxzZvXf9azRr4m7feRtzI8+gcsjTZsBAYAAA==
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peprstores.pepr.dev
spec:
  group: pepr.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              additionalProperties:
                type: string
  scope: Namespaced
  names:
    plural: peprstores
    singular: peprstore
    kind: PeprStore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepr-object-storage-operator-store
  namespace: pepr-system
rules:
  - apiGroups:
      - pepr.dev
    resources:
      - peprstores
    resourceNames:
      - ''
    verbs:
      - create
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepr-object-storage-operator-store
  namespace: pepr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepr-object-storage-operator-store
subjects:
  - kind: ServiceAccount
    name: pepr-object-storage-operator-store
    namespace: pepr-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-object-storage-operator-watcher
  namespace: pepr-system
  labels:
    app: pepr-object-storage-operator-watcher
    pepr.dev/controller: watcher
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pepr-object-storage-operator-watcher
      pepr.dev/controller: watcher
  template:
    metadata:
      annotations:
        buildTimestamp: '1706289904596'
      labels:
        app: pepr-object-storage-operator-watcher
        pepr.dev/controller: watcher
    spec:
      serviceAccountName: pepr-object-storage-operator
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroup: 65532
      containers:
        - name: watcher
          image: ghcr.io/defenseunicorns/pepr/controller:v0.23.1
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - f05ed85b85867f21496a7a3cf24949ff6d1f76dc16c8bcbd90986875e397ba34
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
          env:
            - name: PEPR_WATCH_MODE
              value: 'true'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: debug
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-object-storage-operator-tls
        - name: module
          secret:
            secretName: pepr-object-storage-operator-module
