apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: s3buckets.dashdays.dev
spec:
  group: dashdays.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["name", "region"]
              properties:
                name:
                  type: string
                  x-kubernetes-validations:
                    - message: name is immutable
                      rule: self == oldSelf
                region:
                  type: string
                  x-kubernetes-validations:
                    - message: region is immutable
                      rule: self == oldSelf
          required:
            - spec
  scope: Namespaced
  names:
    plural: s3buckets
    singular: s3bucket
    kind: S3Bucket
    shortNames:
    - s3b
